# Generated by Django 3.2.7 on 2022-09-22 14:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20220912_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(blank=True, default='channel-art.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
